# Generated by Django 6.0.6 on 2026-06-27 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('year_published', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('program', models.CharField(help_text='Degree, Course, or Program', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Major_Category', models.CharField(max_length=50)),
                ('Year_of_Study', models.CharField(max_length=50)),
                ('Primary_Use_Case', models.CharField(max_length=100)),
                ('Prompt_Engineering_Skill', models.CharField(max_length=50)),
                ('Institutional_Policy', models.CharField(max_length=100)),
                ('Paid_Subscription', models.BooleanField(default=False)),
                ('Pre_Semester_GPA', models.FloatField()),
                ('Weekly_GenAI_Hours', models.FloatField()),
                ('Traditional_Study_Hours', models.FloatField()),
                ('Post_Semester_GPA', models.FloatField()),
                ('Skill_Retention_Score', models.FloatField()),
                ('Tool_Diversity', models.IntegerField()),
                ('Perceived_AI_Dependency', models.IntegerField()),
                ('Anxiety_Level_During_Exams', models.IntegerField()),
                ('prediction', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year_proposed', models.IntegerField(help_text='e.g., 2026')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstones', to='researcher.researcher')),
            ],
        ),
    ]
