# Generated by Django 6.0.6 on 2026-06-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='Anonymous', max_length=100)),
                ('weekly_genai_hours', models.FloatField()),
                ('traditional_study_hours', models.FloatField()),
                ('anxiety_level', models.IntegerField()),
                ('prediction_result', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
